name: PR Validation

on:

  pull_request:

    branches:

      - develop

      - qa

      - main

jobs:

  validate:

    runs-on: self-hosted

    steps:

    - name: Checkout

      uses: actions/checkout@v4

    - name: Verify Python

      run: |

        python3 --version

        pip3 --version

    - name: Activate Virtual Env

      run: |

        source ~/github-runner-venv/bin/activate

        python --version

        pip install -r requirements.txt

    - name: GitLeaks Scan

      uses: gitleaks/gitleaks-action@v2

    # - name: Run Tests

    #   run: |

    #     python3 -m pytest \
    #     --cov=. \
    #     --cov-report=xml

    - name: SonarQube Scan

      run: |

        sonar-scanner \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Trivy Filesystem Scan

      run: |

        trivy fs .
