name: PROD Pipeline

on:

  push:

    branches:

      - main

jobs:

  prod:

    runs-on: self-hosted

    environment:

      name: production

    steps:

    - uses: actions/checkout@v4

    - name: GitLeaks Scan

      uses: gitleaks/gitleaks-action@v2

    - name: Verify Python

      run: |

        python3 --version

        pip3 --version

    - name: Activate Virtual Env

      run: |

        source ~/github-runner-venv/bin/activate

        python --version

        pip install -r requirements.txt
    # - name: Run Tests

    #   run: |

    #     python3 -m pytest \
    #     --cov=. \
    #     --cov-report=xml

    - name: SonarQube Scan

      run: |

        sonar-scanner \
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}

    - name: Trivy Scan

      run: |

        trivy fs .

    - name: Build Docker

      run: |

        docker build \
        -t myapp:prod-${{ github.sha }} .

    - name: Scan Docker Image

      run: |

        trivy image myapp:prod-${{ github.sha }}

    - name: Login ECR

      uses: aws-actions/amazon-ecr-login@v2

    - name: Push Image

      run: |

        docker tag myapp:prod-${{ github.sha }} \
        ${{ secrets.ECR_REPOSITORY }}:prod-${{ github.sha }}

        docker push \
        ${{ secrets.ECR_REPOSITORY }}:prod-${{ github.sha }}

    - name: Configure kubeconfig

      run: |

        echo "${{ secrets.KUBECONFIG_PROD }}" > kubeconfig

        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy PROD

      run: |

        export KUBECONFIG=$PWD/kubeconfig

        kubectl apply -f k8s/prod/
