name: QA  Pipeline

on:

  push:

    branches:

      - qa

jobs:

  dev:

    runs-on: self-hosted

    steps:

    - uses: actions/checkout@v4

    - name: GitLeaks

      uses: gitleaks/gitleaks-action@v2

    - name: Install dependencies

      run: |

        python3 -m pip install -r requirements.txt --break-system-packages

    - name: Flake8

      run: |

        python3 -m flake8 .

    - name: Unit Tests

      run: |

        python3 -m pytest

    - name: SonarQube

      uses: SonarSource/sonarqube-scan-action@v6

      env:

        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Trivy FS Scan

      run: |

        trivy fs .

    - name: Build Docker Image

      run: |

        docker build -t flask-app:qa-${{ github.sha }} .

    - name: Trivy Image Scan

      run: |

        trivy image flask-app:qa-${{ github.sha }}

    - name: Stop Existing Container

      run: |

        docker rm -f flask-qa || true

    - name: Run Container

      run: |

        docker run -d --name flask-qa -p 5000:5000 flask-app:qa-${{ github.sha }}
